services:
  app:
    build:
      context: .
      args:
          CATALOG_CREDENTIALS: ${CATALOG_CREDENTIALS}
          CATALOG_PRODUCT_SHOPTET_XML_URL: ${CATALOG_PRODUCT_SHOPTET_XML_URL}
    container_name: virtual-catalog-app
    expose:
      - "9000"

  web:
    image: nginx:alpine
    container_name: virtual-catalog-web
    ports:
      - "8802:80"
    volumes:
      - .:/app
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - app
